---
- name: Create an instance
  hosts: localhost
  gather_facts: no

  vars_files:
   - var
    
  tasks:

    - name: Configure Google Cloud SDK
      command: gcloud beta auth activate-service-account --key-file="{{ credentials_file }}"
      become: yes
      tags:
      - sqlcloud  

    - name: enable Cloud SQL APIs
      command: gcloud services enable sqladmin.googleapis.com
      tags:
      - sqlcloud

    #- name: wait for a couple of minutes
    # pause:
    #    minutes: 2
    #  tags:
    # - sqlcloud

    - name: boot SQL instance
      command: gcloud beta sql instances create "{{ sql_name }}" --database-version=POSTGRES_11 --tier=db-custom-1-3840 --zone="{{ zone }}" --network=projects/"{{ project_id }}"/global/networks/default --no-assign-ip
      register: data

    - name: set postgres password
      command: gcloud sql users set-password postgres  --instance "{{ sql_name }}" --password "123456"
      tags:
      - sqlcloud

    - name: create a database
      gcp_sql_database:
       name: "{{ item }}"
       charset: utf8
       instance: "{{ sql_name }}"
       project: "{{ project_id }}"
       auth_kind: serviceaccount
       service_account_file: "{{ credentials_file }}"
       state: present
      with_items:
       - identity
       - messaging
       - payment
       - trip
       - vehicle
       
       
