---
- name: Create VM
  hosts: localhost
  connection: local
  gather_facts: no
  
  vars:
    service_account_email: postgres-servers@macro-truck-257415.iam.gserviceaccount.com
    credentials_file: /home/darya_olejnik/macro-truck-257415-9cda3c9848e5.json
    project_id: macro-truck-257415
    machine_type: f1-micro
    image: cos-69-10895-385-0
    zone: europe-north1-a

  tasks:
   - name: Launch instances
     gce:
      instance_names: app-instance-1       
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      zone: "{{ zone }}"
      external_ip: none
      tags: 
      - webserver
      - http-server
      - https-server
     register: gce
   - debug:
        var: gce
   - name: Save hosts data
     add_host:
      hostname: "{{ item.private_ip }}"
      groupname: gce_instaces_java
     with_items: "{{ gce.instance_data }}"
   - debug:
       var: hostname
   - name: Wait for SSH for instances
     wait_for:
      delay: 10
      host: "{{ item.private_ip }}"
      port: 22
      state: started
      timeout: 60
     with_items: "{{ gce.instance_data }}"

- name: Configure Hosts
  hosts: gce_instaces_java
#  become: yes
#  become_method: sudo
  gather_facts: no
  roles:
  - docker-compose


