---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars_files:
   - var
  
  tasks:
   - name: Create gce load balancer
     gce_lb:
      name: lbserver2
      external_ip: demo3
      state: present
      region: us-central1
      members: ["us-central1-a/"{{conteiner_optimized_name}}""]
      httphealthcheck_name: hc
      httphealthcheck_port: 80
      httphealthcheck_path: "/"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"


