---
- name: install postgresql on Ubuntu or Debian
  hosts: localhost
#  become: yes
#  become_method: sudo
  connection: local
  gather_facts: no
  
  vars:
    service_account_email: postgres-servers@macro-truck-257415.iam.gserviceaccount.com
    credentials_file: /home/darya_olejnik/macro-truck-257415-9cda3c9848e5.json
    project_id: macro-truck-257415
    machine_type: f1-micro
    image: debian-9
    zone: europe-north1-a
  tasks:
  - name: Launch instances
    gce:
      instance_names: postgres-instance       
      machine_type: "{{ machine_type }}"
      image: "{{ image }}"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"
      zone: "{{ zone }}"
      tags: webserver
    register: gce
  - debug:
      var: gce
  - name: Save hosts data
    add_host:
      hostname: "{{ item.public_ip }}"
      groupname: gce_instaces_java
    with_items: "{{ gce.instance_data }}"
  - debug:
      var: hostname
  - name: Wait for SSH for instances
    wait_for:
      delay: 1
      host: "{{ item.public_ip }}"
      port: 22
      state: started
      timeout: 30
    with_items: "{{ gce.instance_data }}"
  
- name: Configure Hosts
  hosts: gce_instances_java
  become: yes
  become_method: sudo
  roles:
  - install_postgresql
