---
# tasks file for install_java

- name: Update and upgrade apt packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: install jdk
  become: true
  apt: name=default-jdk state=latest

- name: install lsof
  apt: name=lsof state=latest

- name: install SumoCollector
  shell: |
      wget "https://collectors.sumologic.com/rest/download/linux/64" -O SumoCollector.sh && chmod +x SumoCollector.sh

- name: install postgresql-client
  become: true
  apt: name=postgresql-client-common state=latest

- name: postgresql-client
  become: true
  apt: name=postgresql-client state=latest

- name: install zookeeper
  shell: |
       mkdir -p /home/zookeeper
       cd /home/zookeeper
       wget  https://downloads.apache.org/zookeeper/zookeeper-3.6.0/apache-zookeeper-3.6.0-bin.tar.gz
       tar -zxf apache-zookeeper-3.6.0-bin.tar.gz
       mkdir -p /home/zookeeper/data

- name: Config zookepeer
  template: src=zoo.j2 dest=/home/zookeeper/apache-zookeeper-3.6.0-bin/conf/zoo.cfg          
 
- name: start zookeeper
  shell: |
     /home/zookeeper/apache-zookeeper-3.6.0-bin/bin/zkServer.sh start

 
