---
- name: Create Load balancer and PostgreSQL
  hosts: localhost
  gather_facts: no

  vars_files:
   - var
    
  tasks:
   - name: Create gce load balancer
     gce_lb:
      name: loadbalancer
      external_ip: demo3
      state: present
      region: us-central1
      members: ["{{ zone }}/{{ conteiner_optimized_name }}"]
      httphealthcheck_name: hc
      httphealthcheck_port: 8080
      httphealthcheck_path: "/"
      service_account_email: "{{ service_account_email }}"
      credentials_file: "{{ credentials_file }}"
      project_id: "{{ project_id }}"


   - name: Configure Google Cloud SDK
     command: gcloud beta auth activate-service-account --key-file="{{ credentials_file }}"
     become: yes
     tags:
     - sqlcloud  

   - name: Enable Cloud SQL APIs
     command: gcloud services enable sqladmin.googleapis.com
     tags:
     - sqlcloud

    - name: Time for the above adjustments to be applied properly
      pause:
        minutes: 1
      tags:
     - sqlcloud

   - name: Boot SQL instance
     command: gcloud beta sql instances create "{{ sql_name }}" --database-version=POSTGRES_11 --tier=db-custom-1-3840 --zone="{{ zone }}" --network=projects/"{{ project_id }}"/global/networks/default --no-assign-ip
     register: data
    
   - name: Write private ip 
     become: yes
     local_action: shell echo "{{ data.stdout_lines[1] }}"| awk '{print $6}' > /home/pass/env.txt

   - name: Set postgres password
     command: gcloud sql users set-password "{{ db_user }}" --instance "{{ sql_name }}" --password "{{ pass }}"
      
   - name: Write db password and user
     become: yes
     local_action: shell echo '{{ pass }}\n{{ db_user }}' >> /home/pass/env.txt
      
   - name: Run env processing script
     become: yes
     script: ./cloudsql_var.sh
      
   - name: Create a database
     gcp_sql_database:
      name: "{{ item }}"
      charset: utf8
      instance: "{{ sql_name }}"
      project: "{{ project_id }}"
      auth_kind: serviceaccount
      service_account_file: "{{ credentials_file }}"
      state: present
     with_items:
      - identity
      - messaging
      - payment
      - trip
      - vehicle
